# Generated by Django 4.0.2 on 2025-11-28 02:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_hall_rename_show_time_moviesession_start_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moviesession',
            old_name='start',
            new_name='show_time',
        ),
        migrations.RemoveField(
            model_name='moviesession',
            name='hall',
        ),
        migrations.AddField(
            model_name='moviesession',
            name='cinema_hall',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='db.cinemahall'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Hall',
        ),
    ]
